### ISSUE TITLE
Reading whole file into memory

### ISSUE THREAD

**Issue by sheremeta2018** [huylv1/cmc-90poe#1]
[This](https://github.com/huylv1/cmc-90poe/blob/6cf29ddb1e3cfa6590061e9eeb4add267d2a6332/src/main/java/com/cmc/util/PortUtil.java#L71C1-L71C1) method reads whole file with ports information into the memory. Could you please improve the memory consumption for reading file content?

**Comment by huylv1** [comment]
Yes, I will let you know when it is finished

**Comment by huylv1** [comment]
@sheremeta2018 Hello, reading file content algorithm has been improved. Check it out.

**Comment by huylv1** [comment]
reading file content algorithm has been improved
