### ISSUE TITLE
@EventListener annotation to load port on startup

### ISSUE THREAD

**Issue by sheremeta2018** [huylv1/cmc-90poe#2]
Why don't to use @EventListener annotation (or another approach such @PostConstruct, @EventListener, etc to initialize ports loading instead of [static methods](https://github.com/huylv1/cmc-90poe/blob/6cf29ddb1e3cfa6590061e9eeb4add267d2a6332/src/main/java/com/cmc/CmcTestApplication.java#L20)?)

**Comment by huylv1** [comment]
Hi, thanks for the suggestion, i refactored the code so it can be loaded using command-line arguments at the application starts up

**Comment by huylv1** [comment]
it can be loaded using command-line arguments at the application starts up. If there's no file then default file on the classpath will be loaded
