### ISSUE TITLE
Having Lombok already configured, please migrate this class to support Lombok

### ISSUE THREAD

**Issue by sheremeta2018** [huylv1/cmc-90poe#3]
Support Lombok instead of explicit getters/setters [here](https://github.com/huylv1/cmc-90poe/blob/6cf29ddb1e3cfa6590061e9eeb4add267d2a6332/src/main/java/com/cmc/vo/PortVO.java#L8)

**Comment by huylv1** [comment]
Yes, i'll do it

**Comment by huylv1** [comment]
Done
