### ISSUE TITLE
Such approach will duplicate all data in DB on second service run with not inmemory DB

### ISSUE THREAD

**Issue by sheremeta2018** [huylv1/cmc-90poe#4]
[Such approach](https://github.com/huylv1/cmc-90poe/blob/6cf29ddb1e3cfa6590061e9eeb4add267d2a6332/src/main/java/com/cmc/util/PortUtil.java#L76) will dup[locate all data in DB on second service run with not inmemory DB

**Comment by huylv1** [comment]
I agree with you. I will check if a particular key exists in the DB

**Comment by huylv1** [comment]
Check added
