### ISSUE TITLE
Tests is loading whole dataset into memory

### ISSUE THREAD

**Issue by sheremeta2018** [huylv1/cmc-90poe#5]
Tests [is loading](https://github.com/huylv1/cmc-90poe/blob/6cf29ddb1e3cfa6590061e9eeb4add267d2a6332/src/test/java/com/cmc/CmcTestApplicationTests.java#L18) whole dataset into memory, better to use mocks

**Comment by huylv1** [comment]
I will add the test file with a few port

**Comment by huylv1** [comment]
Done
